version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: merchant_postgres
    ports:
      - "5430:5432"
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: merchant_backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    command: >
      bash -c "
        echo 'Running migrations...' &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        echo 'Starting Gunicorn...' &&
        gunicorn merchantproject.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60
      "

    networks:
      - backend

  merchant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: merchant_frontend
    restart: unless-stopped
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend1
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: merchantproject-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
